import Footer from "@/components/Footer";
import Header from "@/components/Header";
import MarqueeBanner from "@/components/MarqueeBanner";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header lang={params.lang} />
        <MarqueeBanner />
        {children}
        <div id="modal-root-content" />
        <Footer />
      </body>
    </html>
  );
}
